### ISSUE TITLE
User Profile sometimes appears empty

### ISSUE THREAD

**Issue by cdw9** [plone/plone.app.users#76] opened 2018-08-02 17:09 UTC
Tested on Plone 5.1.0.1, 5.1.3-pending

Steps to Reproduce:
* As an admin, go to Site Setup > Users & Groups > Member Fields
* Add a new field, like 'Phone Number'. Set the field to display in the user profile and registration form
* Back on the Users tab, add a new user
* After the user is added, click on their name in the users listing. It may appear empty. If it does not, log in as admin in a new browser and view the profile, it will likely be empty.

Note that the data isn't actually missing, I was able to put a pdb into the user-information template and get the user's properties. Their data is safe as long as you don't click Save on the empty profile page.

The data displays again after restarting the instance, but then may disappear again after another user has been added

**Comment by lukebrannon** [comment] 2018-09-19 21:26
Confirmed. Plone 5.1
Plone 5.1.0.1 (5110)
CMF 2.2.12
Zope 2.13.26
Python 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
PIL 4.3.0 (Pillow)

**Comment by rileydog** [comment] 2018-10-05 00:50
I am having the identical issue.

**Comment by wkbkhard** [comment] 2018-12-03 16:10
I am having the identical issue too - it seems if I restart the Instance/the client after I added a member, this isn't an issue anymore, but I can't just keep restarting everytime  I add a member. Any troubleshooting found?

**Comment by rileydog** [comment] 2018-12-03 21:43
sadly, no.   I am still occasionally get the problem.  I posed on community.plone (https://community.plone.org/t/is-anyone-else-having-this-issue-with-user-data-not-being-saved/7257) and had experienced programmer @lukebrannon  study issue and post on community.

**Comment by wkbkhard** [comment] 2018-12-11 14:43
So, I am looking into this problem now. I printed the widget Informations in the Macro and the widgets seem to be empty. May be there is a problem with the function in the view. I'll keep you posted. By the way, I can't reproduce the problem after I restarted my client...

**Comment by wkbkhard** [comment] 2018-12-12 08:59
Hi. I'm not certain, but I just exported the Profiles (including member_data.xml und userschema.xml) and put them into my Theme-Profile-Folder. Afterwards i reinstalled the theme, added a new user, logged in (as the new user) and got on my "personal-information" page. This time my fields weren't empty anymore. May be this could be a solution?

**Comment by terapyon** [comment] 2019-09-03 06:58
We have same problem on Plone 5.2 on Python 3.7. We checked Plone default site is no problem, but we got the problem when we have quick-installed our custom product.

**Comment by terapyon** [comment] 2019-09-03 07:01
@cdw9 Did you fix this issue? or Do you have any workaround?

**Comment by cdw9** [comment] 2019-09-03 13:19
@terapyon the only workaround I found was to restart the instance. But the data may "disappear" again after another user is added.

**Comment by terapyon** [comment] 2019-09-04 01:26
@cdw9 Thank you for your workaround. But it is very troublesome for managing a lot of users.
However, Plone default has never happened it, I think. I think it related any customize, but I don't know what is related.

**Comment by terapyon** [comment] 2020-03-30 10:16
@cdw9 Do you have any idea for resolved without restarting.

**Comment by cdw9** [comment] 2020-03-30 13:13
@terapyon Sorry, I do not.

**Comment by gutow** [comment] 2020-09-19 15:53
I am seeing this in a new install of 5.2.1 as well. This needs a fix other than restarting the instance after users are added. I am currently not in a position to trace the problem.

**Comment by ekulos** [comment] 2021-04-06 15:48
this bug still presents in Plone 5.2.3 (5210). I tested with a new Plone without any custom modules.

I investigated this bug and after opening the @@new-user form the schema of @@user-information changes from  **plone.supermodel.model.member-fields** to **InterfaceClass plone.app.users.browser.interfaces.IAccountPanelForm**
with this schema the check on https://github.com/plone/plone.app.users/blob/master/plone/app/users/browser/account.py#L81
fails and an  AttributeError(name) is raised, but is catched.

**Comment by csanahuja** [comment] 2021-12-13 11:30
I just hit this problem aswell in Plone 5.2.5 (5213)

And after reading ekulos report all I did was commeting this line:
https://github.com/plone/plone.app.users/blob/master/plone/app/users/browser/register.py#L59

I don't know why it is required but without it the problem goes away and edition / creation keeps working as the schema it is not changed.

**Comment by tkimnguyen** [comment] 2021-12-13 12:59
@csanahuja no test failures when you do that?

**Comment by csanahuja** [comment] 2021-12-13 13:38
@tkimnguyen Not sure if I did something wrong but I get the same result either way (with/without change)
The 5 failures are 5 robots test not finding a control.

I did
```
# Added 'plone.app.robotframework' to buildout
sudo -u plone_buildout ./bin/buildout -c .src/plone.app.users/buildout.cfg
./src/plone.app.users/bin/test
```


The result
```
Total: 53 tests, 5 failures, 0 errors and 0 skipped in 1 minutes 46.500 seconds.
```

**Comment by csanahuja** [comment] 2021-12-14 17:06
After a while I got an error on creation, I suspect it is because the usage of the `_v_` attribute and having different clients/instances.

So I have remade the function to not use it:
```
def getRegisterSchema():
    schema = getFromBaseSchema(
        ICombinedRegisterSchema,
        form_name=u'On Registration'
    )
    return schema
````

I will report back if another error popups after this change

**Comment by csanahuja** [comment] 2021-12-16 16:04
Ok after more digging and some headache I think I got a solution, hideous but working.

As ekulos described when you visit the @@new_user view the adapter is provided and the @@user-information stops to load the information of the user. 

What confused me more is that I had another custom user-information view that could be called on the Plone Site or in other context (i.e a Folder) and was not working only when called on a Plone Site.

So back to the line:
```
provideAdapter(AccountPanelSchemaAdapter, (IPloneSiteRoot,), schema)
````

This somehow makes the schema of user-information view to change on Plone Site context. I tried to understand why but this is too much black magic / zope for me. Maybe an elegant solution could be to rewrite that line to only adapt the @@new_user view if that's even possible.

**WARNING**: The hideous part

I made an exact copy of `AccountPanelSchemaAdapter` class (do not try to make this class inherit from the original) called `AccountPanelSchemaRegisterAdapter` and rewrite the `provideAdapter` that way:
```
provideAdapter(AccountPanelSchemaRegisterAdapter, (IPloneSiteRoot,), schema)
```
So it does not change the user-information schema

Full code:

```
class IAccountPanelRegisterForm(Interface):
    """ IAccountPanelRegisterForm
    """


class AccountPanelSchemaRegisterAdapter(object):
    """Data manager that gets and sets any property mentioned
       in the schema to the property sheet
    """
    context = None
    schema = IAccountPanelRegisterForm

    def __init__(self, context):
        mt = getToolByName(context, 'portal_membership')
        userid = context.REQUEST.form.get('userid')
        if (userid and mt.checkPermission('Plone Site Setup: Users and Groups',
                                          context)):
            self.context = mt.getMemberById(userid)
        else:
            self.context = mt.getAuthenticatedMember()

    def _getProperty(self, name):
        value = self.context.getProperty(name, '')
        if value == '':
            value = None
        if value:
            # PlonePAS encodes all unicode coming from PropertySheets.
            return safe_unicode(value)
        return value

    def _setProperty(self, name, value):
        if isinstance(value, set):
            value = list(value)
        if value and isinstance(self.schema[name], schema.Choice):
            value = str(value)
        return self.context.setMemberProperties(
            {name: value}, force_empty=True
        )

    def __getattr__(self, name):
        print(self.schema)
        if name in self.schema:
            if isinstance(self.schema[name], NamedBlobImage):
                # any image is the portrait
                return self.get_portrait()
            # In schema and no explicit handler, assume it's in the property
            # sheet
            return self._getProperty(name)
        raise AttributeError(name)

    def __setattr__(self, name, value):
        if name not in self.schema or hasattr(self.__class__, name):
            # Either not part of the schema or dealt with by an explicit
            # property
            return super(AccountPanelSchemaRegisterAdapter, self).__setattr__(name, value)
        if isinstance(value, NamedBlobImage):
            # any image is stored as portrait
            return self.set_portrait(value)

        return self._setProperty(name, value)

    @property
    def portal(self):
        return getToolByName(self.context, 'portal_url').getPortalObject()

    def get_portrait(self):
        """If user has default portrait, return none"""
        mt = getToolByName(self.context, 'portal_membership')
        value = mt.getPersonalPortrait(self.context.getId())
        if isDefaultPortrait(value, self.portal):
            return None
        return NamedBlobImage(value.data, contentType=value.content_type,
                              filename=getattr(value, 'filename', None))

    def set_portrait(self, value):
        mt = getToolByName(self.context, 'portal_membership')
        member_id = self.context.getId()
        if value is None:
            previous = mt.getPersonalPortrait(member_id)
            if not isDefaultPortrait(previous, self.portal):
                mt.deletePersonalPortrait(str(member_id))
        else:
            portrait_file = value.open()
            portrait_file.filename = value.filename
            mt.changeMemberPortrait(portrait_file, str(self.context.getId()))

    portrait = property(get_portrait, set_portrait)

    @property
    def wysiwyg_editor(self):
        return self._getProperty('wysiwyg_editor')

    @wysiwyg_editor.setter
    def wysiwyg_editor(self, value):
        if value is None:
            # set property that the site-default from the registry is used
            # since both 'None' and None result in plaintexteditor
            value = ''
        return self._setProperty('wysiwyg_editor', value)


def getRegisterSchema():
    schema = getFromBaseSchema(
        ICombinedRegisterSchema,
        form_name=u'On Registration',
    )
    provideAdapter(AccountPanelSchemaRegisterAdapter, (IPloneSiteRoot,), schema)
    return schema
```

**Comment by csanahuja** [comment] 2021-12-24 12:45
Sorry, I deleted my previous post as it was missleading, I hope this one is not.

So there are two functions to get the schema:
https://github.com/plone/plone.app.users/blob/cbc647498d2d28da25b3cd3e078b5b33299839c3/plone/app/users/browser/userdatapanel.py#L100
https://github.com/plone/plone.app.users/blob/cbc647498d2d28da25b3cd3e078b5b33299839c3/plone/app/users/browser/register.py#L49

I think they replace each other their adapters so when the schema is cached they stop replacing the adapters leading to the schema switch.

I did rewrite the two functions deleting the schema caching part

```
def getRegisterSchema():
    schema = getFromBaseSchema(
        ICombinedRegisterSchema,
        form_name=u'On Registration',
    )
    provideAdapter(AccountPanelSchemaAdapter, (IPloneSiteRoot,), schema)
    return schema

def getUserDataSchema():
    schema = getFromBaseSchema(
        IUserDataSchema,
        form_name=u'In User Profile',
    )
    provideAdapter(UserDataPanelAdapter, (IPloneSiteRoot,), schema)
    provideAdapter(UserDataPanelAdapter, (INavigationRoot,), schema)
    return schema
```

**Comment by mauritsvanrees** [comment] 2022-10-05 23:30
I am seeing this too at a site that we migrated this week from 4.3 to 6.0, and that I talk about next week at the Plone conference. I am having a look, but this is some seriously complicated code, with too much indirection.

**Comment by wkbkhard** [comment] 2022-10-14 11:56
> Hi. I'm not certain, but I just exported the Profiles (including member_data.xml und userschema.xml) and put them into my Theme-Profile-Folder. Afterwards i reinstalled the theme, added a new user, logged in (as the new user) and got on my "personal-information" page. This time my fields weren't empty anymore. May be this could be a solution?

This helped me the other day, but still don't know if it could anyone else?

**Comment by mauritsvanrees** [comment] 2022-10-18 15:38
What I see:

- Create a Plone 6.0.0b3 site (or use buildout.coredev).
- Add a test field to the user properties in the user data schema in the UI.
- Add a user `test1` for testing, fill in all fields. Fine to do this as admin.
- Restart for good measure.
- Go to the user information page, http://localhost:8080/Plone/@@user-information?userid=test1. All is fine.
- Go to the registration form, but don't fill anything in. Visiting is enough. http://localhost:8080/Plone/@@new-user
- Go back to the user information page of user test1. The fields are empty.

So what goes wrong?

- The user information page is handled by the [`UserDataPanel`](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/userdatapanel.py#L63) class.
- When accessing the `schema`, this calls the `getUserDataSchema` function, which calls [this code](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/userdatapanel.py#L121):

```
provideAdapter(UserDataPanelAdapter, (IPloneSiteRoot,), schema)
```

- So the [`UserDataPanelAdapter`](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/userdatapanel.py#L26) is found when loading the user information page.
- When you go to the registration page, the [`AddUserForm`](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/register.py#L623) is used.
- This inherits from `BaseRegistrationForm` in the same file.
- When accessing the `schema`, this [calls](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/register.py#L74-L76) the `getRegisterSchema` function, which calls [this code](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/register.py#L59):

```
provideAdapter(AccountPanelSchemaAdapter, (IPloneSiteRoot,), schema)
```

- Now the next time that you visit the user information page, you start on top again, getting the `UserDataPanel` form which calls `getUserDataSchema`. Same as before, so all should be well, right? Wrong.
- The first call of `getUserDataSchema` got the schema and stored it on a volatile attribute `_v_userdata_schema` (or `_v_userdata_manager_schema `) on the portal.
- The next calls of `getUserDataSchema` see this attribute, get the schema from there, and **do not call provideAdapter**.
- Now `z3c.form` does its magic somewhere and gets a data adapter for a field, say the fullname field. And what does it find? Not the `UserDataPanelAdapter`, but the `AccountPanelSchemaAdapter`.
- And what schema does this adapter have? [`IAccountPanelForm`](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/account.py#L51), which is [practically empty](https://github.com/plone/plone.app.users/blob/3.0.0b4/plone/app/users/browser/interfaces.py#L6).
- So it user information page can show no information.

One small remark: calling `provideAdapter` over and over again with the same information, or only differing in the first argument, does not result in dozens of adapters being registered. They overwrite each other. I feared there might be a leak here, where the adapter registry would grow and grow, but that seems to work fine.

Let me first add this comment, before I lose it in an accident. :-)

**Comment by mauritsvanrees** [comment] 2022-10-18 15:41
So how do we solve this mess? One way, as indicated by others above, is to completely ignore the volatile attributes: do not use this caching.  But this code *is* called quite a lot when looking at user information, so I would rather keep this.

What I am thinking of, is this: whenever we set the volatile attribute, remove the other volatile attributes. This means when you switch between user/personal information and registration form, you need to get the schema fresh and provide the adapter. So a bit more work than now, but at least the provides adapter will match the cached schema.

But wait, are the volatile attributes per thread? I think so. So you can only remove them from the current thread, which means this idea does not completely work.

We could cache it on the request instead of the portal. Does that seem like a good idea? I can try that.

**Closed** 2022-10-31 14:38 UTC
Labels: 99 tag: Plone 5.x, 01 type: bug, 12 prio: high
